version: '3'

services:
  app-server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/teste_unifor?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: davi
      SPRING_DATASOURCE_PASSWORD: 12345678     
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: frontend 
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/
    ports:
      - "9090:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  
      
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: teste_unifor
      MYSQL_USER: davi
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend  
  
volumes:
  db-data:
  
networks:
  backend:
  frontend: 
  